### ISSUE TITLE
Avoid snappy dependency

### ISSUE THREAD

**Issue by avaly** [JaniAnttonen/winston-loki#9]
It would be nice if this package could avoid the `snappy` dependency, because it requires native binaries to be built.

This is tricky if a project uses the alpine version of node Docker image for production builds. Sure, one could always install all the python dependencies to build those binaries, but it seems overkill.

**Comment by JaniAnttonen** [comment]
True, good suggestion with the optionality.

Since it is a must-have when using protobuf transport, there's no real option when doing that. The protobuf implementation was meant to be a bit of a proof of concept at first, but then it became the default since it got so much love from me.

The JSON part of things needs to be better for sure.

**Comment by cnoelle** [comment]
I think this kind of fallback is problematic, since in Loki the default port used for protobuf is different from the JSON port (9095 vs 3100).

https://github.com/JaniAnttonen/winston-loki/blob/a5547977e6f080ce80657fc90db69dde51ee77a5/src/batcher.js#L50-L60

If protobuf transport is configured and snappy not found you will enter the catch-block here and end up trying to send JSON to the grpc endpoint, which will silently fail. Better fail fast and throw an exception (or don't catch in the first place). 

Having snappy as an optional dependency still makes perfectly sense for the case that JSON transport is configured explicitly.
